### ISSUE TITLE
How to connect to a different Marketcloud app

### ISSUE THREAD

**Issue by niccolosanarico** [Marketcloud/angular-marketcloud-starter#1]
How can I configure this app to connect to my own Marketcloud backend app?

**Comment by theBliz** [comment]
Hi @niccolosanarico you need to change `marketcloud.public` in app/scripts/services/mcFactory.js with the key you can generate from the dashboard's app. 
I'm adding this in the read me, thanks.

**Comment by niccolosanarico** [comment]
Thank you @theBliz, works perfectly.
